<?php

return [
    'enabled' => env('AI_SEARCH_ENABLED', true),
    'openai_api_key' => env('OPENAI_API_KEY'),
    'embedding_model' => env('AI_SEARCH_EMBEDDING_MODEL', 'text-embedding-3-small'),
    'score_threshold' => (float) env('AI_SEARCH_SCORE_THRESHOLD', 0.78),
    'candidate_limit' => (int) env('AI_SEARCH_CANDIDATE_LIMIT', 300),
    'min_query_length' => (int) env('AI_SEARCH_MIN_QUERY_LENGTH', 2),
    'typo_mode' => env('AI_SEARCH_TYPO_MODE', 'fuzzy'),
    'vector_store' => env('AI_SEARCH_VECTOR_STORE', 'database'),
    'limits' => [
        'results' => (int) env('AI_SEARCH_RESULTS_LIMIT', 24),
        'alternatives' => (int) env('AI_SEARCH_ALTERNATIVES_LIMIT', 5),
    ],
    'rerank' => [
        'boost_in_stock' => (float) env('AI_SEARCH_BOOST_IN_STOCK', 0.05),
        'boost_exact_part_number' => (float) env('AI_SEARCH_BOOST_PART_NUMBER', 0.3),
        'boost_brand_match' => (float) env('AI_SEARCH_BOOST_BRAND', 0.1),
        'boost_year_match' => (float) env('AI_SEARCH_BOOST_YEAR', 0.08),
    ],
    'brand_aliases' => [
        'ميتسوبيشي' => 'Mitsubishi',
        'مستبيشي' => 'Mitsubishi',
        'ميتسوبيشى' => 'Mitsubishi',
        'تويوتا' => 'Toyota',
        'هيونداي' => 'Hyundai',
        'هيونداى' => 'Hyundai',
        'كيا' => 'Kia',
        'نيسان' => 'Nissan',
        'مازدا' => 'Mazda',
        'هوندا' => 'Honda',
        'سوزوكي' => 'Suzuki',
        'شانجان' => 'Changan',
        'جيلي' => 'Geely',
        'ام جي' => 'MG',
        'إم جي' => 'MG',
    ],
    'section_aliases' => [
        'رديتر' => 'تبريد',
        'راديتر' => 'تبريد',
        'ماء' => 'تبريد',
        'فرامل' => 'فرامل',
        'بريك' => 'فرامل',
        'مكابح' => 'فرامل',
        'زيت' => 'زيوت',
        'فلتر' => 'فلاتر',
        'فلتر زيت' => 'فلاتر',
        'كهرباء' => 'كهرباء',
        'بطارية' => 'كهرباء',
        'مكيف' => 'تكييف',
    ],
    'vin' => [
        'api_url' => env('VIN_API_URL'),
        'api_key' => env('VIN_API_KEY'),
    ],
    'meilisearch' => [
        'host' => env('MEILISEARCH_HOST'),
        'key' => env('MEILISEARCH_KEY'),
        'index' => env('MEILISEARCH_AI_INDEX', 'products'),
    ],
];
